model:
  model_name: "Qwen/Qwen3-0.6B"
  model_max_length: 2048
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  load_pretrained_weights: true
  trust_remote_code: true
data:
  train:
    datasets:
    - dataset_name: "PromptResponseDataset"
      dataset_kwargs:
        hf_dataset_path: FreedomIntelligence/Medical-R1-Distill-Data-Chinese
        prompt_column: question
        response_column: response (content)
    target_col: "prompt"
training:
  trainer_type: "TRL_SFT"
  save_final_model: true
  save_steps: 100
  max_steps: 10
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  ddp_find_unused_parameters: false
  optimizer: "adamw_torch"
  learning_rate: 2.0e-05
  compile: false
  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 32
  seed: 192847
  use_deterministic: true
  logging_steps: 5
  log_model_summary: false
  empty_device_cache_steps: 50
  output_dir: "trainedmodels/SFT"
  include_performance_metrics: true
